In [15]:
%load_ext autoreload
import sys
from pathlib import Path

sys.path.append(str(Path('..').resolve()))

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [16]:
%autoreload 2
from bot import QuartoCNN
import torch
model = QuartoCNN()
# torch.manual_seed(42)
input_tensor = torch.randn(1, 4, 4, 4)
input_tensor = abs(torch.round(input_tensor/torch.max(input_tensor)))
print(input_tensor)
out1, out2 = model.predict(input_tensor, TEMPERATURE=0.1, DETERMINISTIC=False)
print(out1[:,:5])
print(out2[:,:5])

tensor([[[[0., 1., 1., 0.],
          [0., 1., 0., 0.],
          [1., 1., 0., 0.],
          [0., 0., 1., 0.]],

         [[0., 0., 1., 0.],
          [0., 1., 0., 1.],
          [1., 1., 0., 0.],
          [0., 0., 1., 0.]],

         [[0., 0., 0., 0.],
          [1., 0., 1., 1.],
          [0., 0., 1., 0.],
          [0., 0., 0., 1.]],

         [[1., 1., 1., 0.],
          [0., 0., 0., 0.],
          [1., 0., 0., 1.],
          [0., 0., 0., 0.]]]])
tensor([[12,  5, 12, 14,  3]])
tensor([[9, 4, 2, 4, 4]])
